/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-11-21 09:38:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/png\" href=\"images/Banner_Hit.png\">\r\n");
      out.write("    \r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Tender Management System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/annimate.css\">\r\n");
      out.write("    <link href=\"css/font-awesome.min.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/SpryTabbedPanels.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--link rel=\"stylesheet\" href=\"css/styles.css\"-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Black+Ops+One\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/bootstrap-dropdownhover.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style2.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Now from here the footer section starts-->\r\n");
      out.write("<div class=\"navbar-inverse\" style=\"color:white;padding:10px;margin-bottom:-20px;text-align: center;background-color:blue; border-radius: 0px\">\r\n");
      out.write("                      <span style=\"font-size:1.2em;font-weight:bold;\">Our Amazing Team Members</span>\r\n");
      out.write("</div><br/>\r\n");
      out.write("<div class=\"footer\">    \r\n");
      out.write("  <div class=\"navbar navbar-inverse\" style=\"border-radius: 0px ;margin-bottom:0px\">\r\n");
      out.write("          <div class=\"container-fluid \">\r\n");
      out.write("\r\n");
      out.write("              <br>\r\n");
      out.write("              <!-- Developer 1 Mr. Shashi Raj-->\r\n");
      out.write("                <div class=\"col-md-3 col-xs-12 col-sm-3\" >\r\n");
      out.write("                  <div class=\"col-md-5 col-xs-5 col-sm-5\">\r\n");
      out.write("                    <img src=\"images/Photoscan18.jpg\" class=\"img-responsive img-circle pull-right\" style=\"width:105px;height:130px;\"alt=\"Shashi Raj Site Developer\" title=\"Mr. Shashi Raj\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-7 col-xs-7 col-sm-7\">\r\n");
      out.write("                    <div class=\"developers pull-left\" style=\"font-weight: bold; color:white;text-align: center;\">\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <span style=\"font-size: 1.7em; color:red\">Mr. Jalinder Gandal</span>\r\n");
      out.write("<!--                     <p><span>Web Developer</span></p>\r\n");
      out.write(" -->                 \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              <!-- Developer 2 Ms. Ahana Guchait -->\r\n");
      out.write("                <div class=\"col-md-2 col-xs-12 col-sm-2\">\r\n");
      out.write("                  <div class=\"col-md-5 col-xs-5 col-sm-5\">\r\n");
      out.write("                    <img src=\"images/nun.jpg\" class=\"img-responsive img-circle pull-right\" style=\"width:105px;height:130px;\"alt=\"Ahana Guchait Site Developer\" title=\"Mr. Ahana Guchait\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-7 col-xs-7 col-sm-7\">\r\n");
      out.write("                    <div class=\"developers pull-left\" style=\"font-weight: bold; color:white;text-align: center;\">\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <span style=\"font-size: 1.7em; color:red\">Ms. Siddhi Chavan</span>\r\n");
      out.write("<!--                     <p><span>Web Designer</span></p>\r\n");
      out.write(" -->                    \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              <!-- Developer 3 Ms. Deep Shikha -->\r\n");
      out.write("              <div class=\"col-md-2 col-xs-12 col-sm-2\">\r\n");
      out.write("                <div class=\"col-md-5 col-xs-5 col-sm-5\">\r\n");
      out.write("                  <img src=\"images/deepshikha.png\" class=\"img-responsive img-circle pull-right\" style=\"width:105px;height:130px;\"alt=\"Deep Shikha Site Developer\" title=\"Mr. Deep shikha\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-7 col-xs-7 col-sm-7\">\r\n");
      out.write("                  <div class=\"developers pull-left\" style=\"font-weight: bold; color:white;text-align: center;\">\r\n");
      out.write("                  <br/>\r\n");
      out.write("                  <span style=\"font-size: 1.7em; color:red\">Ms. Mugdha Jathar</span>\r\n");
      out.write("<!--                   <p><span>Web Designer</span></p>\r\n");
      out.write(" -->                  \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("                 <br/>\r\n");
      out.write("                 <!-- <div style=\"color:white;text-align: center;\">\r\n");
      out.write("                      <span>&copy; Copyright 2018</span><p> Aryabhatt Central Library</p>\r\n");
      out.write("                </div> -->\r\n");
      out.write("          </div> <!-- End of container class-->\r\n");
      out.write("    </div><!-- End of navbar class-->\r\n");
      out.write("  </div><!-- End of footer class-->\r\n");
      out.write("  <div class=\"navbar-inverse\" style=\"color:white;padding:05px;margin-bottom:-17px;text-align: center;background-color:green; border-radius: 0px\">\r\n");
      out.write("                      <span style=\"float:left;padding-left: 6.5%\"> </span><span style=\"padding-left:5%;\">&nbsp; Dam Tender Management Portal</span><span style=\"float:right;padding-right: 6%\" class=\"hidden-xs\">&nbsp;...THANKS FOR VISITING...</span>\r\n");
      out.write("</div><br/>\r\n");
      out.write(" <script src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"js/ajax-utils.js\"></script>\r\n");
      out.write("  <script src=\"js/script.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap-dropdownhover.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
